/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DetoxRouteImport } from './routes/detox'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HealthCalculatorRouteImport } from './routes/health-calculator'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TraditionalFoodsRouteImport } from './routes/traditional-foods'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DetoxRoute = DetoxRouteImport.update({
  id: '/detox',
  path: '/detox',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthCalculatorRoute = HealthCalculatorRouteImport.update({
  id: '/health-calculator',
  path: '/health-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TraditionalFoodsRoute = TraditionalFoodsRouteImport.update({
  id: '/traditional-foods',
  path: '/traditional-foods',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/detox': typeof DetoxRoute
  '/disclaimer': typeof DisclaimerRoute
  '/guides': typeof GuidesRouteWithChildren
  '/health-calculator': typeof HealthCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/terms': typeof TermsRoute
  '/traditional-foods': typeof TraditionalFoodsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/detox': typeof DetoxRoute
  '/disclaimer': typeof DisclaimerRoute
  '/health-calculator': typeof HealthCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/terms': typeof TermsRoute
  '/traditional-foods': typeof TraditionalFoodsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/detox': typeof DetoxRoute
  '/disclaimer': typeof DisclaimerRoute
  '/guides': typeof GuidesRouteWithChildren
  '/health-calculator': typeof HealthCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/terms': typeof TermsRoute
  '/traditional-foods': typeof TraditionalFoodsRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/detox'
    | '/disclaimer'
    | '/guides'
    | '/health-calculator'
    | '/privacy-policy'
    | '/recipes'
    | '/terms'
    | '/traditional-foods'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/recipes/$slug'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/detox'
    | '/disclaimer'
    | '/health-calculator'
    | '/privacy-policy'
    | '/recipes'
    | '/terms'
    | '/traditional-foods'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/recipes/$slug'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/detox'
    | '/disclaimer'
    | '/guides'
    | '/health-calculator'
    | '/privacy-policy'
    | '/recipes'
    | '/terms'
    | '/traditional-foods'
    | '/blog_/$slug'
    | '/guides/$slug'
    | '/recipes/$slug'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DetoxRoute: typeof DetoxRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  HealthCalculatorRoute: typeof HealthCalculatorRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RecipesRoute: typeof RecipesRouteWithChildren
  TermsRoute: typeof TermsRoute
  TraditionalFoodsRoute: typeof TraditionalFoodsRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detox': {
      id: '/detox'
      path: '/detox'
      fullPath: '/detox'
      preLoaderRoute: typeof DetoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-calculator': {
      id: '/health-calculator'
      path: '/health-calculator'
      fullPath: '/health-calculator'
      preLoaderRoute: typeof HealthCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traditional-foods': {
      id: '/traditional-foods'
      path: '/traditional-foods'
      fullPath: '/traditional-foods'
      preLoaderRoute: typeof TraditionalFoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof RecipesRoute
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface RecipesRouteChildren {
  RecipesSlugRoute: typeof RecipesSlugRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesSlugRoute: RecipesSlugRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DetoxRoute: DetoxRoute,
  DisclaimerRoute: DisclaimerRoute,
  GuidesRoute: GuidesRouteWithChildren,
  HealthCalculatorRoute: HealthCalculatorRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RecipesRoute: RecipesRouteWithChildren,
  TermsRoute: TermsRoute,
  TraditionalFoodsRoute: TraditionalFoodsRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
